/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/*
* File Name:    SleepCalc
 * Programmer:  Jenny Wang
 * Date:        August 2, 2016
 * Description: This program uses calculates the number of hours a person have spent sleeping during their lives.
 */
public class SleepCalc extends javax.swing.JFrame {

    /**
     * Creates new form SleepCalc
     */
    public SleepCalc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtBday = new javax.swing.JTextField();
        txtBmonth = new javax.swing.JTextField();
        txtByear = new javax.swing.JTextField();
        txtDay = new javax.swing.JTextField();
        txtMonth = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        btnCalc = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        txtDaysAlive = new javax.swing.JTextField();
        txtHoursSlept = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Sleep Calculator");

        jLabel2.setText("Enter Your Birthdate");

        jLabel3.setText("Day");

        jLabel4.setText("Month");

        jLabel5.setText("Year");

        jLabel6.setText("Enter Today's Date");

        jLabel7.setText("Day");

        jLabel8.setText("Month");

        jLabel9.setText("Year");

        txtBday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBdayActionPerformed(evt);
            }
        });

        txtBmonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBmonthActionPerformed(evt);
            }
        });

        btnCalc.setText("Calculate");
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtByear)
                                    .addComponent(txtBmonth)
                                    .addComponent(txtBday))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(35, 35, 35)
                                .addComponent(txtDay))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMonth)
                                    .addComponent(txtYear)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 78, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(17, 17, 17)))
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCalc)
                    .addComponent(btnExit))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHoursSlept)
                    .addComponent(txtDaysAlive))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(txtBday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(txtBmonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(txtByear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCalc)
                        .addGap(18, 18, 18)
                        .addComponent(btnExit)
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDaysAlive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(txtHoursSlept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBdayActionPerformed

    private void txtBmonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBmonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBmonthActionPerformed

        /*description of functionality
    Parameters: none
    Returns: none
    Preconditions: none
    Throws: none
    */    
    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        int bDay, bMonth, bYear, day, month, year;  //inputted dates
        int alive =0;   //days alive
        int aliveYear;  //years alive
        int asleep; //hours asleep
        int leapYear = 0; //number of leap years in person's life
        
        bDay = Integer.parseInt(txtBday.getText());
        bMonth = Integer.parseInt(txtBmonth.getText());
        bYear = Integer.parseInt(txtByear.getText());
        day = Integer.parseInt(txtDay.getText());
        month = Integer.parseInt(txtMonth.getText());
        year = Integer.parseInt(txtYear.getText());
        
        //number of years
        aliveYear=year-bYear;
        //adds leap year if birthday is beginning of leap year
        if (bYear%4==0 && bMonth<3 && !(bMonth==2 && bDay==29))
            leapYear++;
        //counts number of leap years
        for (int i=1; i<=aliveYear; i++){
            if (((bYear+i)%4)==0)
                leapYear++;
        }
        //subtracts a leap year if the current year is a leap year but extra day has not been passed yet
        if (month==1 || (month==2 && day<29))
            leapYear--;
        
        System.out.println(leapYear);
        
        //converts years into days alive
        alive+=aliveYear*365+leapYear;
        //closes gap between birthDAY number and current DAY
        alive+=day-bDay;
        //if month and day is after birthday and birth month
        if (bMonth<month){            
            for (int i=0; i<(month-bMonth); i++){
                //first half of year
                if ((bMonth+i)<=7){
                    if ((((bMonth+i)%2)==0) && ((bMonth+i)!=2))
                        alive+=30;
                    else if ((bMonth+i)==2)
                        alive+=28;
                    else 
                        alive+=31;
                }
                //second half of year
                else if ((bMonth+i)>7){
                    if (((bMonth+i)%2) == 0)
                        alive+=31;
                    else 
                        alive+=30;
                }
            }
        }
        
        //if month and date is before birthday and birth month
        else{
            for (int i=0; i<(bMonth-month); i++){
                //first half of year
                if ((bMonth-i-1)<=7){
                    if ((((bMonth-i-1)%2)==0) && ((bMonth-i-1)!=2))
                        alive-=30;
                    else if ((bMonth-i-1)==2)
                        alive-=28;
                    else 
                        alive-=31;
                }
                //second half of year
                else if ((bMonth-i-1)>7){
                    if (((bMonth-i-1)%2) == 0)
                        alive-=31;
                    else 
                        alive-=30;
                }
            }
        }
        
        //convert days into hours
        asleep = alive*8;
        
        txtDaysAlive.setText("You have been alive for " + Integer.toString(alive) + " day(s)");
        txtHoursSlept.setText("You have slept for " + Integer.toString(asleep) + " hour(s)");
    }//GEN-LAST:event_btnCalcActionPerformed
    
    /*description of functionality
    Parameters: none
    Returns: none
    Preconditions: none
    Throws: none
    */
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0); //exits program
    }//GEN-LAST:event_btnExitActionPerformed

    /*description of functionality
    Parameters: none
    Returns: none
    Preconditions: none
    Throws: none
    */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SleepCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SleepCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SleepCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SleepCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SleepCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalc;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBday;
    private javax.swing.JTextField txtBmonth;
    private javax.swing.JTextField txtByear;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextField txtDaysAlive;
    private javax.swing.JTextField txtHoursSlept;
    private javax.swing.JTextField txtMonth;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
